---
cmdInTerminal: "&cYou can't use this command in the terminal!"

argumentsBlank: "&cPlease do not leave arguments blank!"

invalidTarget: "&cThe target with the name &b{target} &cdoes not exist or is not online!"

invalidInput: "&b<amount>&c is not valid! (1 ≥ <amount: int> ≤ 64)"

sendYourself: "&cYou can't send items to yourself!"

sendAir: "&cYou can't send &b{air} &cto &b{target}&c!"

notEnoughItems: "&cYou don't have enough &b{itemCount} {itemName} &cin hand to send &b{target}&c!"

notEnoughSpace: "&b{target}'s &cinventory doesn't have enough space!"

sentSuccessfully: "&aSent &bx{itemCount} {itemName} &ato &b{target}&a!"

receivedSuccessfully: "&aYou received &bx{itemCount} {itemName} &afrom &b{target}&a!"
...
